### ISSUE TITLE
Missing Design Decisions

### ISSUE THREAD

**Issue by krmaffey** [mlte-team/mlte-framework#21]
From Reviewer 1

"...The solution is proposed in a very high-level view, and some design decisions are missing.

For example, it is not clear why the accuracy requirement negotiation and other requirement negotiation are separated into step 1 and step 3 but not in the same step. It is also not clear how is the generality of the proposed solution with respect to different domains (e.g., different domains may have different metrics for robustness)."

**Comment by JennyNiemann** [comment]
add a sentence in IMT about the experimental nature of ML model dev and why we have two separate collab points instead of just citing [32] / [33]
