### ISSUE TITLE
Improve listings

### ISSUE THREAD

**Issue by krmaffey** [mlte-team/mlte-framework#30]
From reviewer 3

"The paper is overall well-written and understandable. An exception is both listings, which lack a description and discussion to be valuable in the paper...To improve the reading flow, the use of non-descriptive labels (e.g., "to address Problem 2" instead of a describing name) could be reduced."

"Listing 1 lacks a description. What does it actually show/what is specified? Why is it valuable to have tooling that imperatively creates these specifications? Wouldn't you expect that a declarative specification approach is easier to evolve and maintain (i.e., why isn't the specification script the artifact but generates an artifact)?
I understand what you want to show in Listing 2. But I am not convinced that Listing 2 does that (at the core, explanation missing). What I see is that you imperatively write results after an experiment; later you can read them and generate a report. How is that different from today? What does this tooling make better/easier than Jupyter notebooks with standard ML and data science libraries?"

**Comment by JennyNiemann** [comment]
Will look at listing 1 with the figure 1 changes

**Comment by turingcompl33t** [comment]
At the core of the 3rd comment in this issue is:

> What does the MLTE tooling provide to improve the practitioner's experience?

**Comment by krmaffey** [comment]
Collection and then aggregation of evidence showing that a model does indeed meet the requirements of its corresponding system and of the system as a whole
